#!/bin/sh

if [ "x$IP" == "x" ]; then
    IP=`ip a s dev ${iface} \
       | grep '\<inet\>' \
       | sed 's|\s*inet \([0-9.]\+\).*|\1|g'`
fi

generate_conf () {
    if [ "x$IP" == "x" ]; then
        ip route get $DNS > /tmp/net
        read t t gw t t t IP < /tmp/net
        subn=$(echo $IP | cut -f 1-3 -d .)
    else
        subn=$(echo $IP | cut -f 1-3 -d .)
        gw=$subn".1"
    fi
    bcast=$subn".255"
    pool_start=$subn".15"
    pool_end=$subn".250"
    subn=$subn".0"
    subnetmask="255.255.255.0"

cat << EOF > /etc/dhcp/dhcpd.conf
default-lease-time 600;
allow booting;
allow bootp;
log-facility local7;
subnet $subn netmask $subnetmask {
	option routers $gw;
	option subnet-mask $subnetmask;
	option domain-name-servers $DNS;
	option broadcast-address $bcast;
	next-server $IP;
	filename "$PXE_target";
	range $pool_start $pool_end;
}
include "/etc/dhcp/conf.d/$host_file";
EOF

    [ -f /etc/dhcp/conf.d/$host_file ] || touch /etc/dhcp/conf.d/$host_file

    if [ ! -f /tftpboot/mapfile ]; then
cat << EOF2 > /tftpboot/mapfile
# See http://linux.die.net/man/8/tftpd for more info.
#
ri	^[a-z]:				# Remove "drive letters"
rg	\\		/		# Convert backslashes to slashes
rg	([A-Z])		\L\1            # Convert uppercase to lowercase
rg	\#		@		# Convert hash marks to @ signs
rg	/../		/..no../	# Convert /../ to /..no../
e	^ok/				# These are always ok
r	^[^/]		/\0	        # Convert non-absolute files
a	\.pvt$				# Reject requests for private files
EOF2
    fi
}

generate_conf

# Run daemons
     /usr/sbin/dhcpd -4 -f -d --no-pid -cf /etc/dhcp/dhcpd.conf $iface &
exec /usr/sbin/in.tftpd $@
